export const datiAzienda = {
  ragioneSociale: { id: "ragione_sociale", label: "*Ragione sociale" },
  pIva: { id: "piva", label: "*P. Iva" },
  viaCorso: { id: "via_corso_azienda", label: "*Via, Corso" },
  indirizzo: { id: "indirizzo_azienda", label: "*Indirizzo" },
  civico: { id: "civico_azienda", label: "*Civico" },
  cap: { id: "cap_azienda", label: "*CAP" },
  comune: { id: "comune_azienda", label: "*Comune" },
  provincia: { id: "provincia_azienda", label: "*Provincia" },
  rui: { id: "rui_azienda", label: "*Codice RUI" },
  telefono: { id: "telefono_azienda", label: "*Telefono" },
  email: { id: "email_azienda", label: "*E-mail" },
  fax: { id: "fax_azienda", label: "Fax" },
  pec: { id: "pec", label: "PEC" },
};

export const datiResponsabile = {
  cognome: { id: "cognome", label: "*Cognome" },
  nome: { id: "nome", label: "*Nome" },
  cf: { id: "cf", label: "*CF" },
  rui: { id: "rui", label: "*Codice RUI" },
  telefono: { id: "telefono", label: "Telefono" },
  cellulare: { id: "cellulare", label: "*Cellulare" },
  email: { id: "email", label: "*E-mail" },
};

export const datiAnagrafici = {
  cognome: { id: "cognome", label: "*Cognome" },
  nome: { id: "nome", label: "*Nome" },
  cf: { id: "cf", label: "*CF" },
  viaCorso: { id: "via_corso", label: "*Via, Corso" },
  indirizzo: { id: "indirizzo", label: "*Indirizzo" },
  civico: { id: "civico", label: "*Civico" },
  provincia: { id: "provincia", label: "*Provincia" },
  comune: { id: "comune", label: "*Comune" },
  cap: { id: "cap", label: "*CAP" },
  pIva: { id: "piva", label: "*P. Iva" },
  rui: { id: "rui", label: "*Codice RUI" },
  email: { id: "email", label: "*E-mail" },
  cellulare: { id: "cellulare", label: "*Cellulare" },
};

export const datiDittaIndividuale = {
  ragioneSociale: { id: "ragione_sociale", label: "*Ragione sociale" },
  cognome: { id: "cognome", label: "*Cognome" },
  nome: { id: "nome", label: "*Nome" },
  cf: { id: "cf", label: "*CF" },
  pIva: { id: "piva", label: "*P. Iva" },
  provincia: { id: "provincia_azienda", label: "*Provincia" },
  comune: { id: "comune_azienda", label: "*Comune" },
  cap: { id: "cap_azienda", label: "*CAP" },
  viaCorso: { id: "via_corso_azienda", label: "*Via, Corso" },
  indirizzo: { id: "indirizzo_azienda", label: "*Indirizzo" },
  civico: { id: "civico_azienda", label: "*Civico" },
  rui: { id: "rui_azienda", label: "*Codice RUI" },
  cellulare: { id: "cellulare", label: "*Cellulare" },
  email: { id: "email_azienda", label: "*E-mail" },
  fax: { id: "fax_azienda", label: "Fax" },
  pec: { id: "pec", label: "PEC" },
};
